[package]
name = "cadmium"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/mattferraro/cadmium"
authors = ["Matt Ferraro"]
description = "A CAD program written in Rust with a JS front end"
license = "Elastic License 2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.87"
tsify-next = "0.5.3"
truck-meshalgo = { git = "https://github.com/ricosjp/truck.git", rev = "c84318b8dec" }
truck-modeling = { git = "https://github.com/ricosjp/truck.git", rev = "c84318b8dec" }
truck-shapeops = { git = "https://github.com/ricosjp/truck.git", rev = "c84318b8dec" }
truck-polymesh = { git = "https://github.com/ricosjp/truck.git", rev = "c84318b8dec" }
truck-topology = { git = "https://github.com/ricosjp/truck.git", rev = "c84318b8dec" }
truck-stepio = { git = "https://github.com/ricosjp/truck.git", rev = "c84318b8dec" }
serde_json = "1.0.117"
serde = "1.0.202"
itertools = "0.13.0"
svg = "0.17.0"
geo = "0.28.0"
serde_with = "3.4.0"
crc32fast = "1.3.2"
indexmap = "2.1.0"
anyhow = { version = "1.0.86", features = ["backtrace"] }
thiserror = "1.0.61"
strum = { version = "0.26.2", features = ["derive"] }
isotope = { git = "https://github.com/CADmium-Co/ISOtope.git", version = "*", features = ["tsify"] }
paste = "1.0.15"
cadmium-macros = { path = "../cadmium-macros", version = "*" }
log = "0.4.21"
wasm-logger = "0.2.0"

[lib]
crate-type = ["cdylib", "rlib"]
